# Generated by Django 5.1.2 on 2024-10-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Характеристики')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Цифровые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Наличие')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='Кол-во на складе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('main_image', models.ImageField(blank=True, upload_to='products/main/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
